### ISSUE TITLE
AISD zadanie 12/1

### ISSUE THREAD

**Issue by Jakub-Radzik** [WiktorSa/Data-Structures-and-Algorithms#1]
Usuń powtórzenia kodu i wysuń wszystko na wysoki poziom abstrakcji, klasa abstrakcyjna załatwi problem

**Comment by WiktorSa** [comment]
Akurat powtórzenia kodu i nieładna składnia kodu to plaga u mnie (szczególnie gdy trzeba na AiSD napisać trochę na zajęciach, żeby punktów nie stracić a potem nie chce się człowiekowi poprawiać). Na pewno w wakacje przejrzę mój kod i poprawię wszystkie rzeczy co nie wyglądają dobrze. Ale dzięki za zwrócenie uwagi. Postaram się bardziej zwracać uwagę na to żeby kod był lepszy.

**Comment by WiktorSa** [comment]
Listy zostały naprawione. Kod powinien być teraz bardziej przejrzysty. Jeżeli coś jeszcze zauważysz do poprawy to daj znać to się zastanowię czy jest sens poprawiać.
